# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: backend

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name


provider:
  name: aws
  runtime: python3.10
  profile: developer
  region: eu-north-1
  timeout: 100
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::recipemodels/*
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"
  warmup:
    default:
      enabled: true
      events:
        - schedule: "rate(5 minutes)"
      timeout: 500

package:
  individually: false
  exclude:
    - package.json
    - package-lock.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/pytorch_model.bin
    - raw/**
    - .vscode/**
    - .ipynb_checkpoints/**


functions:
  transformImage:
    handler: handler.lambda_handler
    module: app
    memorySize: 6144
    timeout: 300
    events:
      - http:
          path: transform
          method: post
          cors: true
    warmup: 
      default:
        enabled: true

plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
